### ISSUE TITLE
Add Metrics to the snapshot controller

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#142]
Add Metrics to snapshot controller.  Need to be consistent with Metrics in PV/PVC controller.

@jingxu97 to check if Shawn (?) can work on this.

**Comment by saad-ali** [comment]
Fixed in https://github.com/kubernetes-csi/external-snapshotter/pull/227

**Comment by saad-ali** [comment]
@xing-yang @yuxiangqian You should open one a similar bug on the common snapshot controller

**Comment by saad-ali** [comment]
Or I guess we can leave this open to track that

**Comment by xing-yang** [comment]
Sure.

**Comment by yuxiangqian** [comment]
Plan to add following metrics into common controller:
1. end to end latency of the following snapshot operations:
   a. creation (including snapshot cutting and uploading time if any)
   b. deletion
metric name: snapshot_operation_total_seconds
metric type: histogram
labels: driver, operation_name
2. Error counts of operation
metric name: snapshot_operation_error_count
metric type: Counter
labels: driver, operation_name

**Comment by saad-ali** [comment]
You can combine both (latency and count) in to a single metric.

**Comment by msau42** [comment]
Count is strange for a total latency metric that you want to capture across retry loops in the controller.

**Comment by msau42** [comment]
Maybe we can get some guidance from sig-instrumentation in this area. How do we map the K8s reconciliaton model to typical metrics patterns which are generally call-based?

**Comment by yuxiangqian** [comment]
I share the some concern as Michelle, but @saad-ali what's the major benefits of combining them into one? one less TS?
One possibility is to model reconciliation as async-call-based metrics pattern.

**Comment by saad-ali** [comment]
My recommendation is based on this conversation: https://github.com/kubernetes-csi/external-provisioner/pull/386#discussion_r358461293
I'll defer to @logicalhan

**Comment by yuxiangqian** [comment]
Its certainly possible to save the error counter by introducing a new label into the latency histogram. Unlike the csi metrics, there is no well-defined return code ATM in snapshot-controller which could serve as another label. To achieve that, a more well-defined error reporting mechanism needs to be introduced in the snapshot-controller. I will do some more digging.
 could be as simple as three types:
1. Success
2. Retryable
3. Permanent-Failure

since the histogram metric tends to record end to end latency of an operation, the three types could also be used to determinate whether the operation has ended or not.

**Comment by logicalhan** [comment]
> I share the some concern as Michelle, but @saad-ali what's the major benefits of combining them into one? one less TS?

A histogram metric is actually a series of metrics and it includes a count metric. So having another metric for counting is redundant; this is an artifact of the way prometheus exposition format expresses histograms.

**Comment by msau42** [comment]
@logicalhan @saad-ali the challenge here is that this metric is a total latency metric that captures the time across multiple retry loops, so the "count" is really only the number of Snapshot objects that were created.

How much value do you see in also having a per-retry loop metric? In reality, I found that per-loop metric at least for latency has not been very useful because it doesn't map to the user-perceived operations.

**Comment by yuxiangqian** [comment]
> > I share the some concern as Michelle, but @saad-ali what's the major benefits of combining them into one? one less TS?
> 
> A histogram metric is actually a series of metrics and it includes a count metric. So having another metric for counting is redundant; this is an artifact of the way prometheus exposition format expresses histograms.

this is slightly different than a pure count, it's an error count not total operation count. It also makes the situation more complex as the end to end latency metric tries to record the whole duration of an operation from the controller took it to either it succeeded or permanently failed. An operation might go through multiple reconcile loops before it's done, and same errors could happen. I probably need to add a cache to record starting timestamps for each operation, and mixing error count into the cache might bring another complexity as we do not have well defined error status as CSI does.

**Comment by yuxiangqian** [comment]
this is not done yet. #280 only supplies the metrics utility functions, implementation in controller is still needed.

**Comment by yuxiangqian** [comment]
cc @andili99
