### ISSUE TITLE
Add event for snapshotting in progress

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-snapshotter#268]
We have a similar event when creating a PVC that we're waiting for the driver to provision.

/kind feature

**Comment by xing-yang** [comment]
@msau42 you want this event to be on VolumeSnapshot object, not VolumeSnapshotContent, right?

**Comment by msau42** [comment]
Correct

**Comment by xing-yang** [comment]
If we are adding this on VolumeSnapshot object, we can do it after we've created VolumeSnapshotContent in the common controller.  It is not very precise but probably close enough.

The sidecar is the one that sends request to the CSI driver but it only has access to the VolumeSnapshotContent object.

We can also have the common controller check the VolumeSnapshotBeingCreated annotation (which is being added in this PR: https://github.com/kubernetes-csi/external-snapshotter/pull/261) and add event when the annotation is added.  That will have a delay.

**Comment by xing-yang** [comment]
Discussed about this at today's CSI implementation meeting and had a conclusion:
We'll add an event on the VolumeSnapshot API object after we've created VolumeSnapshotContent in the common controller.

Take a look of the create event on PVC for example.

**Comment by zhucan** [comment]
@xing-yang Can you show me the example for creating event on PVC?

**Comment by xing-yang** [comment]
We need to make a call like this:
https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L661

The event will be added on VolumeSnapshot object and eventype should be v1.EventTypeNormal.  Take a look of the caller of updateSnapshotErrorStatusWithEvent() to see how the parameters are passed in.  We don't need to call updateSnapshotErrorStatusWithEvent() here because we only need to create a normal event on VolumeSnapshot object, no need to update status.

**Comment by xing-yang** [comment]
The message itself should be similar to this one:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L1617

**Comment by zhucan** [comment]
@xing-yang we only need to add the event after the volumesnapshotcontent  be created?

**Comment by xing-yang** [comment]
> @xing-yang we only need to add the event after the volumesnapshotcontent be created?

Yes.
