### ISSUE TITLE
restoresize  in volumesnapshotcontent is show in  bytes

### ISSUE THREAD

**Issue by Madhu-1** [kubernetes-csi/external-snapshotter#342]
```
oc get volumesnapshot
NAME               READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS             SNAPSHOTCONTENT                                    CREATIONTIME   AGE
rbd-pvc-snapshot   true         rbd-pvc                             1Gi           csi-rbdplugin-snapclass   snapcontent-a87d6944-0476-4c92-9a59-61c760bafe35   32s            33s
```
```
oc get volumesnapshotcontent
NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER                       VOLUMESNAPSHOTCLASS       VOLUMESNAPSHOT     AGE
snapcontent-6f5a1c27-e6b6-41c0-a43a-1459165e6a7c   true         1073741824    Delete           rook-ceph.rbd.csi.ceph.com   csi-rbdplugin-snapclass   rbd-pvc-snapshot   21
```

the restore size is shown in bytes format as well in volume snapshot output its show in formatted size(either in Mib/Gib ...)  it would be good we volumesnapshotcontent size also show in human-readable format(converted to Mib,Gib etc)

**Comment by Madhu-1** [comment]
cc @xing-yang

**Comment by xing-yang** [comment]
That's because RestoreSize in VolumeSnapshot and VolumeSnapshotContent have different types.  It is int in the content.  This is just to print out what is actually in the content.  I don't think converting is good idea, but that would defeat the purpose.  The size is VolumeSnapshot is converted based on size in the Content.  Whatever shown in VolumeSnapshot status is user's view.  Content is supposedly to be seen by admin only.
