### ISSUE TITLE
Use patch instead of update

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-snapshotter#368]
To reduce the number of update failures due to resources being out of date, it is recommended to use patch instead of update. For updates where it's important that no other field in the object got modified, then you can include the object version in the patch.

**Comment by xing-yang** [comment]
@Kartik494 do you want to work on this?  Thanks.

**Comment by Kartik494** [comment]
@xing-yang  yes i will take a look in this

/assign

**Comment by xing-yang** [comment]
See example here: https://github.com/kubernetes/kubernetes/blob/v1.20.0-alpha.0/pkg/volume/util/resize_util.go#L165

**Comment by Kartik494** [comment]
Hi @xing-yang @msau42  for just confirmation if i am right here i have to patch the objects for resources persistentvolumes persistentvolumeclaim,volumesnapshotclasses and persistentvolumecontents?

**Comment by xing-yang** [comment]
@Kartik494 this is only for patching the Status field of VolumeSnapshot and VolumeSnapshotContent in external-snapshotter repo.

**Comment by xing-yang** [comment]
For example, 
https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L740
https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L764

Search for any usage of Update and UpdateStatus in the code.

**Comment by xing-yang** [comment]
We do an update of PVC as well for a finalizer.  So we can consider that one as well.  I'll say work on VolumeSnapshot and VolumeSnapshotContent Update and UpdateStatus first.

**Comment by Kartik494** [comment]
> We do an update of PVC as well for a finalizer. So we can consider that one as well. I'll say work on VolumeSnapshot and VolumeSnapshotContent Update and UpdateStatus first.

@xing-yang Thanks for sharing information, i will work on this first.

**Comment by ggriffiths** [comment]
@msau42 @xing-yang should we rename this to "snapshot controller and snapshotter sidecar fail to update CRs with "object has been modified"" or something similar, as the patch implementation in https://github.com/kubernetes-csi/external-snapshotter/pull/480 did not fix this?

I have a feeling that this problem might be happening because the snapshot-controller and snapshotter sidecar are both responsible for updating the `VolumeSnapshotContent` object. As a result, the snapshot-controller 

If we follow a model like this, maybe these errors would be eliminated:
| Controller     | Object | Access |
| ---        |    ----   |          --- |
| Snapshot Controller      | VolumeSnapshot       | Read & Write |
| Snapshot Controller      | VolumeSnapshotContent       | Read-only   |
|  Snapshotter Sidecar   |    VolumeSnapshot    |   Read-only   |
| Snapshotter Sidecar   |  VolumeSnapshotContent       |  Read & Write   |

This would mostly involve removing a few "VolumeSnapshotContent" update calls from the Snapshot Controller, and having the snapshotter sidecar handle these updates instead.

/remove-lifecycle stale

**Comment by xing-yang** [comment]
@ggriffiths Sure, go ahead and rename the issue.

**Comment by xing-yang** [comment]
@ggriffiths Do we still need to keep this issue open?

**Comment by ggriffiths** [comment]
No we can close this. If another simillar error comes up, we can open a new issue for any further update -> patch replacements.
