### ISSUE TITLE
Unable to create volume snapshot

### ISSUE THREAD

**Issue by Sg-23** [kubernetes-csi/external-snapshotter#590]
I am facing issue while creating a volume snapshot of pvc on Openshift cluster v4.6.29 .

I am unable to create volume snapshot with the following error in events :
Waiting for a snapshot test-project/k10-csi-snap-vtmhd4spq2bxc6rt to be created by the CSI driver.

The provisioner for the pv is rook-ceph.rbd.csi.ceph.com.

**Comment by xing-yang** [comment]
What is the "Provisioner" field in StorageClass?
Did you provide a VolumeSnapshotClass?  What is the "Driver" field in VolumeSnapshotClass?

**Comment by Sg-23** [comment]
"Provisioner" field in StorageClass is rook-ceph.rbd.csi.ceph.com
yes i have provided VolumeSnapshotClass.
"Driver" field in VolumeSnapshotClass is rook-ceph.rbd.csi.ceph.com

**Comment by xing-yang** [comment]
Who is the maintainer of this CSI Driver rook-ceph.rbd.csi.ceph.com?  Can you ask them to take a look of the logs?

**Comment by Kartik494** [comment]
@Sg-23 I think you can check with status of your pvc and [volumesnapshotclass](https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/examples/kubernetes/snapshotclass-v1.yaml) otherwise this operation run successfully , or as suggested by xing you can ping for maintainer of CSI Driver rook-ceph.rbd.csi.ceph.com to take a look on this

**Comment by Madhu-1** [comment]
@Sg-23 please open an issue with https://github.com/rook/rook with logs I can take a look at it.

**Comment by Sg-23** [comment]
@Madhu-1 I have opened an issue with rook. 
[Issue](https://github.com/rook/rook/issues/8728)

**Comment by Madhu-1** [comment]
@Sg-23 feel free to close this issue

**Comment by Sg-23** [comment]
ok thanks
