### ISSUE TITLE
checkandUpdateContentStatusOperation will createSnapshot again and over again if vendor create snapshot is not idempotent

### ISSUE THREAD

**Issue by xujianhai666** [kubernetes-csi/external-snapshotter#624]
test my vendor snapshot api， when apply snapshot.yaml, I found my api received many create snapshot request from my vendor, that is stanger, I deep into code, and found that if snapshot status is not ready, snapshotter sidecar will call method createSnapshotWrapper forever, which cause my create snapshot api high qps
    In my opinion, snaoshotter sidecar should call GetSnapshotStatus to get ready status instead of call CreateSnapshot
    some code now like below:
```
func (ctrl *csiSnapshotSideCarController) checkandUpdateContentStatusOperation(content *crdv1.VolumeSnapshotContent) (*crdv1.VolumeSnapshotContent, error) {
    .....
    if content.Spec.Source.SnapshotHandle != nil {
       // static mode
        .....
       return updatedContent, nil
    }
    return ctrl.createSnapshotWrapper(content)
}
```

**Comment by xing-yang** [comment]
The CreateSnapshot RPC is required to be idempotent. If a driver does not support idempotency, it should be fixed to support it. 
One important reason we decided to call CreateSnapshot instead of ListSnapshots is because ListSnapshots is optional. It is possible for a driver to support CreateSnapshot but not ListSnapshots, while it is not possible for a driver to support ListSnapshots but not CreateSnapshot.
