### ISSUE TITLE
RestoreSize should be nil instead of zero

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-snapshotter#639]
When a CSI driver returns `CreateSnapshotResponse.snapshot.size_bytes = 0`, it says that the [the snapshot size is unspecified](https://github.com/container-storage-interface/spec/blob/5b0d4540158a260cb3347ef1c87ede8600afb9bf/csi.proto#L1140).

External-snapshotter (and perhaps the snapshot-controller too) copies this zero to VolumeSnapshotContent / VolumeSnapshot `status.RestoreSize`. But zero here means that the minimal PVC size is 0 bytes. [`nil` should be used for unknown PVC size](https://github.com/jsafrane/external-snapshotter/blob/8751eb0ca5b33a8a3c2589d506b48cc26684e0cd/client/apis/volumesnapshot/v1/types.go#L174).

**Comment by xing-yang** [comment]
There's a gap between how we handle size in K8s vs the definition in CSI. Similarly, volume size is undefined when it is 0.
https://github.com/container-storage-interface/spec/blob/v1.5.0/csi.proto#L470
In external-provisioner, we ignore 0 returned by the driver and use whatever requested by the user because Kube API server does not support a 0 size:
https://github.com/kubernetes-csi/external-provisioner/blob/v3.0.0/pkg/controller/controller.go#L788

The purpose for this snapshot size field is to make sure the new volume created from a snapshot is bigger or equal to this size. If it is 0, we'll always use the specified volume size as it is bigger. If it is unspecified, we also use the specified volume size as there's nothing to compare with.
