### ISSUE TITLE
6.0.1 release uses 5.0.1 image 

### ISSUE THREAD

**Issue by alex0z1** [kubernetes-csi/external-snapshotter#750]
file `./deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml` in 
https://github.com/kubernetes-csi/external-snapshotter/archive/refs/tags/v6.0.1.tar.gz

uses `gcr.io/k8s-staging-sig-storage/snapshot-controller:v5.0.1` image
should it be v6.0.1 ?

**Comment by xing-yang** [comment]
The image v6.0.1 was built automatically when we cut the release v6.0.1. Therefore we updated the images in the deploy yaml file afterwards.  That is the reason why you see v5.0.1 in the tar file.
If we update the image version before the image was available, there is a risk that the image may never be available due to some build issues. This is rare but it did happen in the past.

**Comment by Jainbrt** [comment]
This issue has been fixed with PR #770.

**Comment by Jainbrt** [comment]
@xing-yang should we close this issue ?
