### ISSUE TITLE
There is no `client/v6.2.1` tag while the `v6.2.1` tag exists

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-csi/external-snapshotter#827]
/kind bug

**What happened**:
There is no `client/v6.2.1` tag while the [`v6.2.1`](https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v6.2.1) exists.

**What you expected to happen**:
The `client/v6.2.1` tag to exist.

**How to reproduce it**:
```
% go get  github.com/kubernetes-csi/external-snapshotter/client/v6@v6.2.1
go: github.com/kubernetes-csi/external-snapshotter/client/v6@v6.2.1: reading github.com/kubernetes-csi/external-snapshotter/client/go.mod at revision client/v6.2.1: unknown revision client/v6.2.1
```

**Anything else we need to know?**:

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xing-yang** [comment]
@ialidzhikov Thanks for reporting this.

There isn't any client side changes between v6.2.0 and v6.2.1 so it is not necessary to cut client/v6.2.1.  There were earlier releases where we only cut server side but not client side release.

registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.0 was not built successfully due to timeout.
v6.2.1 was cut so that we can have registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.1.
